title: Grav
default_lang: en
author:
  name: 'Joe Bloggs'
  email: joe@example.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: long
  size: 1000
  delimiter: '==='
blog:
  route: /blog
